In [ ]:
import numpy as np #Analysis
import pandas as pd #Analysis
import seaborn as sns #Visualization
import matplotlib
import matplotlib.pyplot as plt #Visualization
%matplotlib inline
matplotlib.style.use('seaborn-poster')
sns.set_style('whitegrid')

import warnings
warnings.filterwarnings("ignore")

In [ ]:
train = pd.read_csv('Data/train.csv')
test = pd.read_csv('Data/test.csv')

In [ ]:
train.head(5)

In [ ]:
train.info()

In [ ]:
train.describe()

In [ ]:
train.describe(include=['O'])

In [ ]:
sns.countplot(x='Survived',hue='Pclass',data=train)

In [ ]:
train[['Pclass', 'Survived']].groupby(['Pclass'], as_index=False).mean().sort_values(by='Survived', ascending=False)

In [ ]:
sns.countplot(x='Survived',hue='Sex',data=train)

In [ ]:
train[['Sex', 'Survived']].groupby(['Sex'], as_index=False).mean().sort_values(by='Survived', ascending=False)

In [ ]:
grid = sns.FacetGrid(train,row='Embarked',col='Survived')
grid.map(sns.barplot,'Sex','Fare',ci=None)

In [ ]:
sns.heatmap(train.isnull(),yticklabels=False,cbar=False)

In [ ]:
sns.heatmap(test.isnull(),yticklabels=False,cbar=False)

In [14]:
train.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)
test.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)

In [15]:
train.drop(['Fare'],axis=1,inplace=True)
test.drop(['Fare'],axis=1,inplace=True)

In [16]:
train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0            1         0       3    male  22.0      1      0        S
1            2         1       1  female  38.0      1      0        C
2            3         1       3  female  26.0      0      0        S
3            4         1       1  female  35.0      1      0        S
4            5         0       3    male  35.0      0      0        S

In [17]:
test.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch Embarked
0          892       3    male  34.5      0      0        Q
1          893       3  female  47.0      1      0        S
2          894       2    male  62.0      0      0        Q
3          895       3    male  27.0      0      0        S
4          896       3  female  22.0      1      1        S

In [18]:
train['Sex'] = train['Sex'].map({'female': 1, 'male': 0}).astype(int)
test['Sex'] = test['Sex'].map({'female': 1, 'male': 0}).astype(int)

In [19]:
train.head(1)
test.head(1)

PassengerId  Pclass  Sex   Age  SibSp  Parch Embarked
0          892       3    0  34.5      0      0        Q

In [20]:
train['Age'].fillna(value=train['Age'].median(),inplace=True)
test['Age'].fillna(value=train['Age'].median(),inplace=True)

In [21]:
train['Embarked'].fillna(value=train['Embarked'].mode()[0],inplace=True)
test['Embarked'].fillna(value=train['Embarked'].mode()[0],inplace=True)

In [22]:
train['Embarked'] = train['Embarked'].map({'C': 0, 'Q': 1, 'S': 2}).astype(int)
test['Embarked'] = test['Embarked'].map({'C': 0, 'Q': 1, 'S': 2}).astype(int)

In [23]:
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null int32
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Embarked       891 non-null int32
dtypes: float64(1), int32(2), int64(5)
memory usage: 48.8 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Sex            418 non-null int32
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Embarked       418 non-null int32
dtypes: float64(1), int32(2), int64(4)
memory usage: 19.7 KB
None


In [24]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

C:\Users\Ravi.RAVI-DRAGOON\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [25]:
x_all = train.drop(['Survived', 'PassengerId'], axis=1)
y_all = train['Survived']
X_train, X_test, y_train, y_test = train_test_split(x_all, y_all, test_size=0.28, random_state=100)

In [26]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
rfc_prediction = rfc.predict(X_test)
rfc_score=accuracy_score(y_test, rfc_prediction)
print(rfc_score)
print("-"*50)
print(classification_report(y_test,rfc_prediction))
print("-"*50)
print(confusion_matrix(y_test,rfc_prediction))
print("-"*50)

0.812
--------------------------------------------------
             precision    recall  f1-score   support

          0       0.80      0.90      0.85       147
          1       0.83      0.69      0.75       103

avg / total       0.81      0.81      0.81       250

--------------------------------------------------
[[132  15]
 [ 32  71]]
--------------------------------------------------


In [27]:
svm = SVC()
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
svc_score = accuracy_score(y_test, y_pred)
print(svc_score)
print("-"*50)
print(classification_report(y_test,y_pred))
print("-"*50)
print(confusion_matrix(y_test,y_pred))
print("-"*50)

0.796
--------------------------------------------------
             precision    recall  f1-score   support

          0       0.79      0.89      0.84       147
          1       0.81      0.66      0.73       103

avg / total       0.80      0.80      0.79       250

--------------------------------------------------
[[131  16]
 [ 35  68]]
--------------------------------------------------


In [28]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
logreg_prediction = logreg.predict(X_test)
logreg_score=accuracy_score(y_test, logreg_prediction)
print(logreg_score)
print("-"*50)
print(classification_report(y_test,logreg_prediction))
print("-"*50)
print(confusion_matrix(y_test,logreg_prediction))
print("-"*50)

0.788
--------------------------------------------------
             precision    recall  f1-score   support

          0       0.79      0.88      0.83       147
          1       0.79      0.66      0.72       103

avg / total       0.79      0.79      0.78       250

--------------------------------------------------
[[129  18]
 [ 35  68]]
--------------------------------------------------


In [29]:
X_train = train.drop(['Survived', 'PassengerId'], axis=1)
X_test = test.drop(['PassengerId'], axis=1)
y_train = train['Survived']

In [30]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
rfc_prediction = rfc.predict(X_test)
submission = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": rfc_prediction
    })
submission.to_csv('SubmissionFile/Titanic_RFC.csv', index=False)

In [31]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
logreg_prediction = logreg.predict(X_test)
submission = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": logreg_prediction
    })
submission.to_csv('SubmissionFile/Titanic_Logreg.csv', index=False)

In [32]:
svm = SVC()
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
submission = pd.DataFrame({
        "PassengerId": test["PassengerId"],
        "Survived": y_pred
    })
submission.to_csv('SubmissionFile/Titanic_SVC.csv', index=False)